repos:
-  repo: local
   hooks:
   -  id: elm-format
      name: elm-format
      language: system
      entry: ./node_modules/.bin/elm-format --validate
      pass_filenames: true
      files: \.elm$
